apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-cephfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs-fuse
  resources:
    requests:
      storage: 10Gi
